/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufrj_ppgi_parser_SaxParserJNI */

#ifndef _Included_br_ufrj_ppgi_parser_SaxParserJNI
#define _Included_br_ufrj_ppgi_parser_SaxParserJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufrj_ppgi_parser_SaxParserJNI
 * Method:    createBaseFacts
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_br_ufrj_ppgi_parser_SaxParserJNI_createBaseFacts
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
